repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pylint_core
        name: pylint_core
        entry: bash -c 'find core -name "*.py" -exec pylint "{}" +'
        language: python
        types: [ python ]
        pass_filenames: false
        verbose: true
        args:
          - --exit-zero
          - --output-format=colorized
          - --rcfile=.pylintrc
          - --fail-under=9
      - id: pylint_web
        name: pylint_web
        entry: bash -c 'find web -name "*.py" -exec pylint "{}" +'
        language: python
        types: [ python ]
        pass_filenames: false
        verbose: true
        args:
          - --exit-zero
          - --output-format=colorized
          - --rcfile=.pylintrc_web
          - --fail-under=9.5